version: '3'
services:
  traefik:
    image: "traefik:v3.0"
    container_name: traefik
    command:
      # Docker configuration
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      # API and dashboard configuration
      - "--api.dashboard=true"
      - "--api.insecure=true"
      # Entrypoints configuration
      - "--entrypoints.web.address=:80"
    ports:
      - "80:80"
      - "8080:8080"  # Dashboard port
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.dashboard.rule=Host(`traefik.localhost`)"
      - "traefik.http.routers.dashboard.service=api@internal"
      - "traefik.http.routers.dashboard.entrypoints=web"

  app:
    container_name: app
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      APP_DEBUG: "true"
      APP_ENV: "local"
      APP_KEY: "base64:DJYTvaRkEZ/YcQsX3TMpB0iCjgme2rhlIOus9A1hnj4="
      APP_URL: "http://app.localhost"
      DB_CONNECTION: mysql
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: app_database
      DB_USERNAME: app_user
      DB_PASSWORD: app_password
    depends_on:
      db:
        condition: service_healthy
    entrypoint: |
      bash -c "
        echo 'Waiting for database connection...'
        while ! nc -z db 3306; do
          sleep 1
        done
        
        php artisan migrate --force
        apache2-foreground
      "
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.app.rule=Host(`app.localhost`)"
      - "traefik.http.routers.app.entrypoints=web"
      - "traefik.http.services.app.loadbalancer.server.port=80"

  db:
    image: mysql:5.7
    container_name: db
    restart: always
    environment:
      MYSQL_DATABASE: app_database
      MYSQL_USER: app_user
      MYSQL_PASSWORD: app_password
      MYSQL_ROOT_PASSWORD: app_root_password
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "app_user", "--password=app_password"]
      interval: 5s
      timeout: 5s
      retries: 5
    labels:
      - "traefik.enable=false"

volumes:
  db_data: