groups:
  - name: node
    rules:
      - alert: HighCPUUsage
        expr: 100 - (avg by(instance) (irate(node_cpu_seconds_total{mode="idle"}[5m])) * 100) > 80
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High CPU usage (instance {{ $labels.instance }})"
          description: "CPU usage is above 80%\n  VALUE = {{ $value }}%"

      - alert: HighMemoryUsage
        expr: (node_memory_MemTotal_bytes - node_memory_MemFree_bytes - node_memory_Buffers_bytes - node_memory_Cached_bytes) / node_memory_MemTotal_bytes * 100 > 80
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High memory usage (instance {{ $labels.instance }})"
          description: "Memory usage is above 80%\n  VALUE = {{ $value }}%"

  - name: containers
    rules:
      - alert: ContainerHighCPUUsage
        expr: sum by(name) (rate(container_cpu_usage_seconds_total{container!=""}[5m]) * 100) > 80
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High container CPU usage (container {{ $labels.name }})"
          description: "Container CPU usage is above 80%\n  VALUE = {{ $value }}%"

      - alert: ContainerHighMemoryUsage
        expr: container_memory_usage_bytes{container!=""} / container_spec_memory_limit_bytes * 100 > 80
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High container memory usage (container {{ $labels.name }})"
          description: "Container memory usage is above 80%\n  VALUE = {{ $value }}%" 