# tasks file for install_docker
- name: Update and upgrade apt packages
  apt:
    update_cache: yes
    upgrade: yes

# - name: Debug host variables
#   debug:
#     var: hostvars[inventory_hostname]

- name: Install required packages
  apt:
    name:
      - git
      - curl
      - zip
      - unzip
      - tzdata
      - docker.io
      - docker-compose
    state: present

# - name: Debug current user
#   debug:
#     msg: "Current user is {{ lookup('env', 'USER') }} (from environment)."


# - name: Debug current user as become
#   debug:
#     msg: "Current user {{ lookup('env', 'USER') }} (from environment)."
#   become: true

- name: Add current user to Docker group
  command: usermod -aG docker "{{ lookup('env', 'USER') }}"
  become: true

- name: Start Docker service
  service:
    name: docker
    state: started
    enabled: true