# all:
#   hosts:
#     azure_vm_one:
#       ansible_host: deplinux-test.westeurope.cloudapp.azure.com
#       ansible_user: appuser99
#       ansible_ssh_private_key_file: /home/appuser99/.ssh/id_terraform
#       ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
hosts:
  localhost:
    vars:
      ansible_user: appuser99
      ansible_connection: local